### ISSUE TITLE
blaze.join fails on MySQL tables with foreign keys

### ISSUE THREAD

**Issue by dgolden1** [blaze/blaze#1264] opened 2015-10-06 18:37 UTC
I have a MySQL database with two tables that have a foreign key relationship. Attempting to join them using `blaze.join` fails within the `datashape` module with an error of the form

```
TypeError: DataShape map[int32, {
 ... (contents omitted)
}]  is not NumPy-compatible
```

Reproduced with Blaze 0.8.3+10.g9e83642 and datashape 0.4.7+12.g409fc4b

### Create dummy MySQL database
```mysql
CREATE DATABASE `test`;
USE `test`;
CREATE TABLE `table_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `table_b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `id_a` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `b_to_a` FOREIGN KEY (`id_a`) REFERENCES `table_a` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `table_a` (`name`) VALUES ('name_a_1');
INSERT INTO `table_a` (`name`) VALUES ('name_a_2');
INSERT INTO `table_a` (`name`) VALUES ('name_a_3');
INSERT INTO `table_b` (`name`, `id_a`) VALUES ('name_b_1', 1);
INSERT INTO `table_b` (`name`, `id_a`) VALUES ('name_b_2', 2);
```

### Join tables with blaze
```python
import blaze
import sqlalchemy

username = '[YOUR_MYSQL_USERNAME]'
db_url = ('mysql+pymysql://%s@localhost/test' % username)
engine = sqlalchemy.create_engine(db_url)
db = blaze.Data(engine)
joined = blaze.join(db['table_a'], db['table_b'], on_left='id', on_right='id_a', how='inner')
```

### Result
From iPython:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8a365ad7ca9e> in <module>()
      6 engine = sqlalchemy.create_engine(db_url)
      7 db = blaze.Data(engine)
----> 8 joined = blaze.join(db['table_a'], db['table_b'], on_left='id', on_right='id_a', how='inner')

/Users/dgolden/.pyenv/versions/3.5.0/lib/python3.5/site-packages/blaze/expr/collections.py in join(lhs, rhs, on_left, on_right, how, suffixes)
    555     for n, promotion in enumerate(map(partial(promote, promote_option=False),
    556                                       left_types,
--> 557                                       right_types)):
    558         if promotion == object_:
    559             raise TypeError(

/Users/dgolden/.pyenv/versions/3.5.0/lib/python3.5/site-packages/datashape/promote.py in promote(lhs, rhs, promote_option)
     38             np.result_type(
     39                 datashape.to_numpy_dtype(left),
---> 40                 datashape.to_numpy_dtype(right),
     41             ),
     42         )

/Users/dgolden/.pyenv/versions/3.5.0/lib/python3.5/site-packages/datashape/coretypes.py in to_numpy_dtype(ds)
   1137     """ Throw away the shape information and just return the
   1138     measure as NumPy dtype instance."""
-> 1139     return to_numpy(ds.measure)[1]
   1140
   1141

/Users/dgolden/.pyenv/versions/3.5.0/lib/python3.5/site-packages/datashape/coretypes.py in to_numpy(ds)
   1170         msr = ds
   1171
-> 1172     return tuple(shape), msr.to_numpy_dtype()
   1173
   1174

/Users/dgolden/.pyenv/versions/3.5.0/lib/python3.5/site-packages/datashape/coretypes.py in to_numpy_dtype(self)
    143
    144     def to_numpy_dtype(self):
--> 145         raise TypeError('DataShape %s is not NumPy-compatible' % self)
    146
    147

TypeError: DataShape map[int32, {id: int32, name: ?string[255]}] is not NumPy-compatible
```

**Comment by ACampbell22** [comment] 2015-10-12 15:26
I am also running into this.

**Comment by llllllllll** [comment] 2015-10-12 16:06
The issue is that we are implicitly following the fkey to the table that it is pointing to. This means that instead of a type of `int32`, your `id` column has a type of `map[int32, {id: int32, name: ?string[255]}]` Which says that it is a mapping (like a dictionary) from `int32` to a record with two fields. I imagine that these fields are the columns of the table you are pointing to.

For right now, you could explicitly pass a dshape to your table by looking at at the current `db.dshape` and manually changing out the `map[int32, {id: int32, name: ?string[255]}]` with just ``int32`. For example:

```python
>>> db.dshape  # assume that this is what your dshape is. It will probably look very similar.
dshape('var * {a: int64, b: float32, id: map[int32, {id: int32, name: ?string[255]}]}')
>>> new_db = bz.Data(engine, dshape='var * {a: int64, b: float32, id: int32}')
```

Note that we swapped out the field type for the `id` column to just be an int32. This will not have blaze attempt to follow the foreign key.
Hopefully this helps fix your immediate problem. We will need to work on making this easier to do. One idea that I have would be to make `follow_fkeys` default to false so that people don't run into this without realizing that we are doing this.

**Comment by drdan14** [comment] 2015-10-12 16:30
@llllllllll thanks for the tip. I can confirm that your solution works on my test database; specifically, I set the `db` variable like:

```python
db = blaze.Data(engine, dshape="""{
  table_a: var * {id: int32, name: ?string[255]},
  table_b: var * {
    id: int32,
    name: ?string[255],
    id_a: int32
    }
  }""")
```

where `id_a` is explicitly set to `int32` instead of its default `map[...]`. Now the `join` works fine. Thanks for the tip!

In the mean time, is there a way to specify the dshape of a single expression instead of the whole database? For example, if I have just one problem table, maybe I could do something like:

```python
db['table_b'].as_dshape('id: int32, name: string[255], id_a: int32']
```

to avoid typing in the schema for the entire database.

Regardless, this approach of explicitly identifying the schema is a functional workaround, but it doesn't scale well for a reasonably large production database with potentially dozens of tables and relationships, like I actually have (not shown). I'd have to type out the entire schema into the Python code, which would break if the underlying database schema ever changed. So your proposed solution of not following foreign keys by default (`follow_fkeys` defaults to fals), or at least making it an option, sounds like a more sustainable one.

**Comment by kwmsmith** [comment] 2015-11-15 21:28
@dgolden1 I've created a follow-up issue regarding foreign keys.  I'm closing this issue, please re-open if something else comes up regarding this specifically.

**Closed by kwmsmith** 2015-11-15 21:28 UTC
Labels: bug, sql
