### ISSUE TITLE
Debugging test failures in the server

### ISSUE THREAD

**Issue by cournape** [blaze/blaze#1383] opened 2016-01-12 09:58 UTC
While testing our packaging of blaze, I got some failures in the server test suite:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/vagrant/src/buildsystem-git/build/master-env/lib/python2.7/site-packages/blaze/server/tests, inifile:
collected 76 items

build/master-env/lib/python2.7/site-packages/blaze/server/tests/test_server.py ....................................FFFFFFsssssss...........................

=================================== FAILURES ===================================
____________ test_server_can_compute_sqlalchemy_reductions[serial0] ____________

test = <FlaskClient <Flask 'blaze.server.server'>>
serial = SerializationFormat(name='pickle', loads=<built-in function loads>, dumps=<functools.partial object at 0x2b3473592aa0>)

    @pytest.mark.parametrize('serial', all_formats)
    def test_server_can_compute_sqlalchemy_reductions(test, serial):
        expr = t.db.iris.petal_length.sum()
        query = {'expr': to_tree(expr)}
        response = test.post(
            '/compute',
            data=serial.dumps(query),
            headers=mimetype(serial)
        )

>       assert 'OK' in response.status
E       assert 'OK' in '500 INTERNAL SERVER ERROR'
E        +  where '500 INTERNAL SERVER ERROR' = <Response streamed [500 INTERNAL SERVER ERROR]>.status

build/master-env/lib/python2.7/site-packages/blaze/server/tests/test_server.py:396: AssertionError
```

and similar 500 errors elsewhere. What's the simplest way for me to look at the traceback of the server in the test suite ? This is for blaze 0.9.0

**Comment by cournape** [comment] 2016-01-12 10:01
I only get this error when using odo 0.4.0. Downgrading to `0.3.4` fix those errors, but I'd like to understand why (the tests pass w/ blaze 0.9.0 + odo 0.4.0 works in conda after all :) )

**Comment by llllllllll** [comment] 2016-01-12 19:26
The server and client are both running in the same process for these tests so there is no traceback anywhere, it is swallowed by flask. When working on the blaze server, I normally debug this situation by setting a breakpoint in `blaze.server.server.compserver` at the top of the function and then step through until I hit the uncaught exception. You can also set the breakpoint right in the `except Exception as e` handler and inspect `e` directly. At least in python 3 there is the `__traceback__` attribute which can be pretty printed with traceback.print_tb`.

Let me know what you find or if you need more help with this.

**Comment by cournape** [comment] 2016-01-14 16:56
Thanks, that was it.

So this is what I am seeing:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/vagrant/src/tmp/blaze-0.9.0, inifile: 
collected 1 items

blaze/server/tests/test_server.py F

=================================== FAILURES ===================================
____________________ test_serialization_endpoints[serial0] _____________________

test = <FlaskClient <Flask 'blaze.server.server'>>
serial = SerializationFormat(name='json', loads=<function <lambda> at 0x10e3c1b8>, dumps=<functools.partial object at 0x10e36578>)

    @pytest.mark.parametrize('serial', all_formats)
    def test_serialization_endpoints(test, serial):
        expr = t.db.iris.petal_length.sum()
        query = {'expr': to_tree(expr)}
        response = test.post(
            '/compute',
            data=serial.dumps(query),
>           headers=mimetype(serial)
        )

blaze/server/tests/test_server.py:410: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/werkzeug/test.py:788: in post
    return self.open(*args, **kw)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/testing.py:108: in open
    follow_redirects=follow_redirects)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/werkzeug/test.py:751: in open
    response = self.run_wsgi_app(environ, buffered=buffered)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/werkzeug/test.py:668: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/werkzeug/test.py:871: in run_wsgi_app
    app_rv = app(environ, start_response)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1836: in __call__
    return self.wsgi_app(environ, start_response)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1820: in wsgi_app
    response = self.make_response(self.handle_exception(e))
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1403: in handle_exception
    reraise(exc_type, exc_value, tb)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1817: in wsgi_app
    response = self.full_dispatch_request()
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1477: in full_dispatch_request
    rv = self.handle_user_exception(e)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1381: in handle_user_exception
    reraise(exc_type, exc_value, tb)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1475: in full_dispatch_request
    rv = self.dispatch_request()
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/flask/app.py:1461: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
blaze/server/server.py:19: in wrapped
    return f(*a, **k)
blaze/server/server.py:114: in authorized
    return f(*args, **kwargs)
blaze/server/server.py:140: in check
    return f(payload, serial)
blaze/server/server.py:422: in compserver
    result = coerce_scalar(result, str(expr.dshape))
blaze/interactive.py:241: in coerce_scalar
    return coerce_(float)
blaze/interactive.py:235: in coerce_to
    return odo(x, typ, **(odo_kwargs or {}))
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/odo/odo.py:91: in odo
    return into(target, source, **kwargs)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/multipledispatch/dispatcher.py:164: in __call__
    return func(*args, **kwargs)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/odo/into.py:43: in wrapped
    return f(*args, **kwargs)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/odo/into.py:53: in into_type
    return convert(a, b, dshape=dshape, **kwargs)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/odo/core.py:44: in __call__
    return _transform(self.graph, *args, **kwargs)
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/odo/core.py:60: in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = rec.array([(563.7000000000004,)], 
      dtype=[('petal_length_sum', '<f8')])
name = None, chunks = None, kwargs = {'dshape': None, 'excluded_edges': set([])}

    @convert.register(Array, tuple(arrays), cost=1.)
    def array_to_dask(x, name=None, chunks=None, **kwargs):
        if chunks is None:
>           raise ValueError("chunks cannot be None")
E           ValueError: chunks cannot be None

../../buildsystem-git/build/master-env/lib/python2.7/site-packages/odo/backends/dask.py:59: ValueError
=========================== 1 failed in 2.40 seconds ===========================
```

W/ odo `0.4.0`, dask `0.7.6`, and blaze `0.9.0`. Is there something more I can do to figure this out ?

**Comment by llllllllll** [comment] 2016-01-14 17:43
Hmm,, what it appears is happening is that the `sum` which should be a scalar datashape of `float64` is instead a `1 * {petal_length_sum: float64}` and is stored in a numpy recarray. in `coerce_scalar` we are trying to route you through dask array but the `chunks` argument was not passed so it is failing. `array_to_dask` in `odo` needs a better error message to better indicate what has caused `chunks` to be None because often it will happen when `array_to_dask` is not the first edge in your path.

I am not able to reproduce this on master so I would like to  see if we can get some more information.
To better understand why you are getting this recarray at all, can you set a breakpoint in `compserver` right after `result = compute(expr, {leaf: dataset}, **compute_kwargs)`. `result` at this point should be a sqlalchemy select. Can you also show `expr.dshape` and `str(expr.dshape)`?

**Comment by cournape** [comment] 2016-01-14 18:16
So result is indeed a `select` object. I got `dshape("?float64")` for expr.dshape.

**Comment by cournape** [comment] 2016-01-14 18:28
If it helps, I can tar my python install (should be relocatable) so that you can look at it ?

**Comment by llllllllll** [comment] 2016-01-14 19:25
one thing to try would be stepping into coerce_scalar until you hit the odo call. Then keep stepping until you get to `odo.core.NetworkDispatcher._transform` right above the loop that looks like `for (A, B, f) in pth`. There you can look at the path that odo is trying to take to go from your select to a float. It should probably not contain anything about dask.

Also, sorry I didn't suggest this earlier, can you try with master of blaze and odo?

**Comment by cournape** [comment] 2016-01-15 10:41
So using both odo and blaze master make the problem disappear. I tried using odo 0.4.0 w/ blaze master, and got back the error. 

Using odo master did fix the problem, whether I use blaze master or 0.9.0.

**Comment by cournape** [comment] 2016-01-15 10:42
Don't know if that's relevant, but I have dask 0.7.6 and numpy 1.9.2 installed

**Comment by llllllllll** [comment] 2016-01-23 20:48
If the issue is fixed in master of odo/blaze then I am not sure what to do. I think someone updated some costs in odo to fix an issue, this might have been fixed by that.

**Closed** 2016-02-12 23:31 UTC
Labels: server, testing
